version: '3.3'

services:

    nodejs:
        container_name: node_tdd
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/src
        depends_on:
            - db
        links:
            - db
        ports:
            - '3000:8080'
        command: >
            npm start
    db:
       image: 'mongo'
       container_name: node_database
       restart: always
       ports:
           - '27018:27017'
       volumes:
           - ./data/db:/data/db
